# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUserFlows():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_studentLogInLogOut(self):
    # Test name: Student - Log In, Log Out
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 960x1048 | 
    self.driver.set_window_size(960, 1048)
    # 3 | click | linkText=Login | 
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    # 4 | click | id=:r1: | 
    self.driver.find_element(By.ID, ":r1:").click()
    # 5 | type | id=:r1: | nima.currie@umsystem.edu
    self.driver.find_element(By.ID, ":r1:").send_keys("nima.currie@umsystem.edu")
    # 6 | type | id=:r3: | pass
    self.driver.find_element(By.ID, ":r3:").send_keys("pass")
    # 7 | click | xpath=//button[@type='submit'] | ${KEY_ENTER}
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    # 8 | click | linkText=Logout | 
    self.driver.implicitly_wait(10)
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 9 | click | xpath=//a[contains(text(),'Return Home')] | 
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Return Home\')]").click()
  
  def test_studentLogInSubmitApplication(self):
    # Test name: Student - Log In, Submit Application
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 960x1048 | 
    self.driver.set_window_size(960, 1048)
    # 3 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
    # 5 | click | id=:R16dmm: | 
    self.driver.find_element(By.ID, ":R16dmm:").click()
    # 6 | type | id=:R16dmm: | nima.currie@umsystem.edu
    self.driver.find_element(By.ID, ":R16dmm:").send_keys("nima.currie@umsystem.edu")
    # 7 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | type | id=:R1admm: | pass
    self.driver.find_element(By.ID, ":R1admm:").send_keys("pass")
    # 9 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
    # 10 | mouseOver | css=.css-ctz29b-MuiButtonBase-root-MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-ctz29b-MuiButtonBase-root-MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | mouseOut | css=.css-ctz29b-MuiButtonBase-root-MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 12 | click | linkText=Apply | 
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    # 13 | click | id=:r1: | 
    self.driver.find_element(By.ID, ":r1:").click()
    # 14 | type | id=:r1: | Nima Currie
    self.driver.find_element(By.ID, ":r1:").send_keys("Nima Currie")
    # 15 | mouseDown | id=mui-component-select-gradDegree | 
    element = self.driver.find_element(By.ID, "mui-component-select-gradDegree")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 16 | mouseUp | css=.MuiBackdrop-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 17 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 18 | click | css=.MuiMenuItem-root:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiMenuItem-root:nth-child(2)").click()
    # 19 | mouseDown | id=mui-component-select-currMajor | 
    element = self.driver.find_element(By.ID, "mui-component-select-currMajor")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 20 | mouseUp | css=.MuiBackdrop-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 21 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 22 | click | css=.MuiMenuItem-root:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiMenuItem-root:nth-child(2)").click()
    # 23 | click | id=:r7: | 
    self.driver.find_element(By.ID, ":r7:").click()
    # 24 | type | id=:r7: | May 2022
    self.driver.find_element(By.ID, ":r7:").send_keys("May 2022")
    # 25 | click | id=:r9: | 
    self.driver.find_element(By.ID, ":r9:").click()
    # 26 | type | id=:r9: | 4.0
    self.driver.find_element(By.ID, ":r9:").send_keys("4.0")
    # 27 | click | css=.MuiGrid-root:nth-child(6) > .MuiFormControl-root:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-root:nth-child(6) > .MuiFormControl-root:nth-child(1)").click()
    # 28 | click | id=:rb: | 
    self.driver.find_element(By.ID, ":rb:").click()
    # 29 | type | id=:rb: | 120
    self.driver.find_element(By.ID, ":rb:").send_keys("120")
    # 30 | click | id=:rd: | 
    self.driver.find_element(By.ID, ":rd:").click()
    # 31 | mouseDown | id=mui-component-select-course | 
    element = self.driver.find_element(By.ID, "mui-component-select-course")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 32 | mouseUp | css=.MuiBackdrop-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 33 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 34 | click | css=.MuiMenuItem-root:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiMenuItem-root:nth-child(2)").click()
    # 35 | mouseDown | id=mui-component-select-grade | 
    element = self.driver.find_element(By.ID, "mui-component-select-grade")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 36 | mouseUp | css=.MuiBackdrop-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 37 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 38 | click | css=.MuiMenuItem-root:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiMenuItem-root:nth-child(2)").click()
    # 39 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 40 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
    # 41 | mouseOver | css=.MuiBox-root:nth-child(3) > .MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiBox-root:nth-child(3) > .MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 42 | click | css=.MuiBox-root:nth-child(3) > .MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBox-root:nth-child(3) > .MuiButton-root").click()
    # 43 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 44 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 45 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 46 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
  
  def test_studentDeleteApplication(self):
    # Test name: Student - Delete Application
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 960x1048 | 
    self.driver.set_window_size(960, 1048)
    # 3 | click | linkText=Login | 
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    # 4 | doubleClick | linkText=Login | 
    element = self.driver.find_element(By.LINK_TEXT, "Login")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 5 | mouseOver | linkText=Login | 
    element = self.driver.find_element(By.LINK_TEXT, "Login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | linkText=Login | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | click | id=:r1: | 
    self.driver.find_element(By.ID, ":r1:").click()
    # 8 | type | id=:r1: | nima.currie@umsystem.edu
    self.driver.find_element(By.ID, ":r1:").send_keys("nima.currie@umsystem.edu")
    # 9 | type | id=:r3: | pass
    self.driver.find_element(By.ID, ":r3:").send_keys("pass")
    # 10 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
    # 11 | mouseOver | css=.css-ctz29b-MuiButtonBase-root-MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-ctz29b-MuiButtonBase-root-MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | mouseOut | css=.css-ctz29b-MuiButtonBase-root-MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 13 | click | linkText=Manage Applications | 
    self.driver.find_element(By.LINK_TEXT, "Manage Applications").click()
    # 14 | mouseOver | linkText=Manage Applications | 
    element = self.driver.find_element(By.LINK_TEXT, "Manage Applications")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 15 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 16 | mouseOut | linkText=Manage Applications | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 17 | click | css=.MuiDataGrid-row:nth-child(1) path | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiDataGrid-row:nth-child(1) path").click()
    # 18 | click | css=.MuiButton-contained:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained:nth-child(2)").click()
    # 19 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 20 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 21 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 22 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
  
  def test_facultyLogInLogOut(self):
    # Test name: Faculty - Log In, Log Out
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 960x1048 | 
    self.driver.set_window_size(960, 1048)
    # 3 | click | linkText=Login | 
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    # 4 | click | id=:r1: | 
    self.driver.find_element(By.ID, ":r1:").click()
    # 5 | type | id=:r1: | admin@umkc.edu
    self.driver.find_element(By.ID, ":r1:").send_keys("admin@umkc.edu")
    # 6 | click | id=:r3: | 
    self.driver.find_element(By.ID, ":r3:").click()
    # 7 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | type | id=:r3: | admin
    self.driver.find_element(By.ID, ":r3:").send_keys("admin")
    # 9 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
    # 10 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 11 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
  
  def test_facultyViewApplications(self):
    # Test name: Faculty - View Applications
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 960x1048 | 
    self.driver.set_window_size(960, 1048)
    # 3 | click | linkText=Login | 
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    # 4 | mouseOver | linkText=Login | 
    element = self.driver.find_element(By.LINK_TEXT, "Login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | linkText=Login | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | click | id=:r1: | 
    self.driver.find_element(By.ID, ":r1:").click()
    # 7 | type | id=:r1: | admin@umkc.edu
    self.driver.find_element(By.ID, ":r1:").send_keys("admin@umkc.edu")
    # 8 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | type | id=:r3: | admin
    self.driver.find_element(By.ID, ":r3:").send_keys("admin")
    # 10 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
    # 11 | click | linkText=View Submissions | 
    self.driver.find_element(By.LINK_TEXT, "View Submissions").click()
    # 12 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 13 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 14 | mouseOver | css=.MuiButton-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 15 | click | css=.MuiButton-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root").click()
  
if __name__ == '__main__':
    framework = TestUserFlows()
    framework.setup_method()
    framework.test_studentLogInLogOut()
    framework.test_studentLogInSubmitApplication()
    framework.test_studentDeleteApplication()
    